/**
 * Copyright (C) 2012 WRML.org <mark@wrml.org>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *         http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.wrml.runtime;

import java.util.List;
import java.util.Map;

/*
 * This class is used to test the method signature code generation (by looking at it's javac-generated bytecode).
 */

interface Z_JavaBytecodeTest<T, nameType extends java.awt.Button, CAPS_LOCK extends List<T>> {

    public <Q> Q[] arrayMeSomething();

    public <A, B> Map<A, B> getAtoB(Class<A> aClass, Class<B> bClass);

    public List<T> getGenericList();

    public List<Integer> getIntegerList();

    public Map<Integer, String> getIntegerToStringMap();

    public String getName();

    public <M extends Map<String, T>> M getNamedTsMap(Class<M> mapTypeNegotiation_aka_please_make_me_a_Map_of_this_type);

    public List<String> getStringList();

    public Map<String, Object> getStringToObjectMap();

    public List<T> getTs();

    public <SHIFT> SHIFT GetWIERD(Class<CAPS_LOCK> WIERD);

    public void setName(String name);

}
